apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: giropops
    service: webserver
  name: giropops
spec:
  containers:
  - image: nginx  
    name: nginx
    resources:
      limits:
        cpu: "0.5"
        memory: "64Mi"
      requests:
        cpu: "0.3"
        memory: "64Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
