apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: giropops
    service: webserver
  name: giropops
spec:
  containers:
  - image: nginx  
    name: webserver
    volumeMounts: 
    - mountPath: /usr/share/nginx/html
      name: nginx-volume
    resources:
      limits:
        cpu: "0.5"
        memory: "128Mi"
      requests:
        cpu: "0.3"
        memory: "64Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: nginx-volume
    emptyDir: 
      sizeLimit: 256Mi 
